### ISSUE TITLE
Your gem has a weird/accidental release structure

### ISSUE THREAD

**Issue by mensfeld** [Dan2552/mundler#1]
Hey,

My name is Maciej Mensfeld and I run a research security project called WhiteSource https://diffend.io.

While reviewing changes for this package I noticed, that it's Github structure and the RubyGems release does not match.
That is, the gem here has a `lib/mundler.rb` etc while the GH release shows your local path: `data/Users/dan2552/Dropbox/experiments/mundler/lib/mundler/mruby.rb`.

I'm reporting this as I think it is not intentional.

Have a great day :)

The full list can be seen here (please click on the "File changes" => "Show toggle") https://my.diffend.io/gems/mundler/0.5.0

**Comment by Dan2552** [comment]
Oh! Whoops 😄. I'm surprised it let me build the gemspec like that actually.

Thanks for letting me know, I think I've resolved the issue with the 0.6.0 release
